[package]
name = "pastel-hn"
version = "0.2.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "*", features = [] }

[dependencies]
tauri = { version = "*", features = [] }
tauri-plugin-shell = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
open = "*"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
